
package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailBoxManagerBean", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailBoxManagerBean {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://server/", className = "server.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://server/", className = "server.SendMessageResponse")
    @Action(input = "http://server/MailBoxManagerBean/sendMessageRequest", output = "http://server/MailBoxManagerBean/sendMessageResponse")
    public void sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addUserMailBox", targetNamespace = "http://server/", className = "server.AddUserMailBox")
    @ResponseWrapper(localName = "addUserMailBoxResponse", targetNamespace = "http://server/", className = "server.AddUserMailBoxResponse")
    @Action(input = "http://server/MailBoxManagerBean/addUserMailBoxRequest", output = "http://server/MailBoxManagerBean/addUserMailBoxResponse")
    public void addUserMailBox(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeUserMailBox", targetNamespace = "http://server/", className = "server.RemoveUserMailBox")
    @ResponseWrapper(localName = "removeUserMailBoxResponse", targetNamespace = "http://server/", className = "server.RemoveUserMailBoxResponse")
    @Action(input = "http://server/MailBoxManagerBean/removeUserMailBoxRequest", output = "http://server/MailBoxManagerBean/removeUserMailBoxResponse")
    public void removeUserMailBox(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteReadMessages", targetNamespace = "http://server/", className = "server.DeleteReadMessages")
    @ResponseWrapper(localName = "deleteReadMessagesResponse", targetNamespace = "http://server/", className = "server.DeleteReadMessagesResponse")
    @Action(input = "http://server/MailBoxManagerBean/deleteReadMessagesRequest", output = "http://server/MailBoxManagerBean/deleteReadMessagesResponse")
    public void deleteReadMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendNews", targetNamespace = "http://server/", className = "server.SendNews")
    @ResponseWrapper(localName = "sendNewsResponse", targetNamespace = "http://server/", className = "server.SendNewsResponse")
    @Action(input = "http://server/MailBoxManagerBean/sendNewsRequest", output = "http://server/MailBoxManagerBean/sendNewsResponse")
    public void sendNews(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAllMessages", targetNamespace = "http://server/", className = "server.ReadAllMessages")
    @ResponseWrapper(localName = "readAllMessagesResponse", targetNamespace = "http://server/", className = "server.ReadAllMessagesResponse")
    @Action(input = "http://server/MailBoxManagerBean/readAllMessagesRequest", output = "http://server/MailBoxManagerBean/readAllMessagesResponse")
    public String readAllMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMessage", targetNamespace = "http://server/", className = "server.DeleteMessage")
    @ResponseWrapper(localName = "deleteMessageResponse", targetNamespace = "http://server/", className = "server.DeleteMessageResponse")
    @Action(input = "http://server/MailBoxManagerBean/deleteMessageRequest", output = "http://server/MailBoxManagerBean/deleteMessageResponse")
    public void deleteMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readNewMessages", targetNamespace = "http://server/", className = "server.ReadNewMessages")
    @ResponseWrapper(localName = "readNewMessagesResponse", targetNamespace = "http://server/", className = "server.ReadNewMessagesResponse")
    @Action(input = "http://server/MailBoxManagerBean/readNewMessagesRequest", output = "http://server/MailBoxManagerBean/readNewMessagesResponse")
    public String readNewMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
