
package ejb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DirectoryManagerBeanService", targetNamespace = "http://ejb/", wsdlLocation = "http://d012-01.int-evry.fr:8080/DirectoryManagerBeanService/DirectoryManagerBean?wsdl")
public class DirectoryManagerBeanService
    extends Service
{

    private final static URL DIRECTORYMANAGERBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIRECTORYMANAGERBEANSERVICE_EXCEPTION;
    private final static QName DIRECTORYMANAGERBEANSERVICE_QNAME = new QName("http://ejb/", "DirectoryManagerBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://d012-01.int-evry.fr:8080/DirectoryManagerBeanService/DirectoryManagerBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIRECTORYMANAGERBEANSERVICE_WSDL_LOCATION = url;
        DIRECTORYMANAGERBEANSERVICE_EXCEPTION = e;
    }

    public DirectoryManagerBeanService() {
        super(__getWsdlLocation(), DIRECTORYMANAGERBEANSERVICE_QNAME);
    }

    public DirectoryManagerBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIRECTORYMANAGERBEANSERVICE_QNAME, features);
    }

    public DirectoryManagerBeanService(URL wsdlLocation) {
        super(wsdlLocation, DIRECTORYMANAGERBEANSERVICE_QNAME);
    }

    public DirectoryManagerBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIRECTORYMANAGERBEANSERVICE_QNAME, features);
    }

    public DirectoryManagerBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectoryManagerBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DirectoryManagerBean
     */
    @WebEndpoint(name = "DirectoryManagerBeanPort")
    public DirectoryManagerBean getDirectoryManagerBeanPort() {
        return super.getPort(new QName("http://ejb/", "DirectoryManagerBeanPort"), DirectoryManagerBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectoryManagerBean
     */
    @WebEndpoint(name = "DirectoryManagerBeanPort")
    public DirectoryManagerBean getDirectoryManagerBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb/", "DirectoryManagerBeanPort"), DirectoryManagerBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIRECTORYMANAGERBEANSERVICE_EXCEPTION!= null) {
            throw DIRECTORYMANAGERBEANSERVICE_EXCEPTION;
        }
        return DIRECTORYMANAGERBEANSERVICE_WSDL_LOCATION;
    }

}
